// File generated by FlutterFire CLI for PRODUCTION project.
// Update this file by running:
// flutterfire configure --project=<production-project-id> --platforms=android,ios,web --out=lib/firebase_options_production.dart
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptionsProduction {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProduction have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProduction have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProduction have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProduction are not supported for this platform.',
        );
    }
  }

  // Temporary fallback values copied from the existing project config.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJpDZkGQrgalc6EqIc0BfgTXtDKOBNlYI',
    appId: '1:386994873681:web:f1bfb01eeea67832461f70',
    messagingSenderId: '386994873681',
    projectId: 'new-lanka-connect-app',
    authDomain: 'new-lanka-connect-app.firebaseapp.com',
    storageBucket: 'new-lanka-connect-app.firebasestorage.app',
    measurementId: 'G-W2JMCKJSBN',
  );

  // Replace with your dedicated production Firebase project's values.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa9L_LiMkTqCVF8wdGB2BV7MEVkcX42i0',
    appId: '1:386994873681:android:9b6c325341a34ca0461f70',
    messagingSenderId: '386994873681',
    projectId: 'new-lanka-connect-app',
    storageBucket: 'new-lanka-connect-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0hY4jdZ42iDp81OHeZ72g3dcYvhkvWMw',
    appId: '1:386994873681:ios:bb83cd29e2d9889c461f70',
    messagingSenderId: '386994873681',
    projectId: 'new-lanka-connect-app',
    storageBucket: 'new-lanka-connect-app.firebasestorage.app',
    iosBundleId: 'com.example.lankaConnect',
  );

}